### ISSUE TITLE
Visualization not working in dark theme

### ISSUE THREAD

**Issue by tonyprinzler** [sghaskell/maps-plus#30]
I'm getting following error using the viz in dark mode

Uncaught TypeError: Cannot read properties of undefined (reading 'styleSheet')
    at child._darkModeInit (/en-US/static/@77015bc7a462/app/leaflet_maps_app/visualizations/maps-plus/visualization.js:311:103)
    at child.updateView (/en-US/static/@77015bc7a462/app/leaflet_maps_app/visualizations/maps-plus/visualization.js:2015:46)
    at child.<anonymous> (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:1314:1607975)
    at child._tryWithAsyncCatch (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:1314:1612370)
    at child.updateView (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:1314:1607927)
    at child._updateView (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:1314:1578927)
    at child._updateView (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:1314:1607871)
    at Subclass.Class.validate (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:829:5886)
    at Subclass.Class.validate (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:1314:1575156)
    at Subclass.Class.validateAll (/en-US/static/@FBDFF6F6AE2E563869C7B0C4F64B3EC1EE00DACD1B32157230D78C951B4C8AC5/build/pages/dark/dashboard_1.1.js:829:6776)

Does someone know why and how to workaround?

**Comment by sghaskell** [comment]
Thanks for reporting. I'll test this out and see what's going on. What version of Splunk are you running?

**Comment by sghaskell** [comment]
Fixed in v4.6.0. The `_darkModeInit` function now identifies the contextmenu sub-stylesheet by scanning cssRules for a `.leaflet-contextmenu` selector rather than taking the first `@import` found. This prevents the `Cannot read properties of undefined (reading 'styleSheet')` error when stylesheet load order changes. Please upgrade to v4.6.0 and reopen if the issue persists.
